kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: helloworld-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-agent
  template:
    metadata:
      labels:
        app: helloworld-agent
    spec:
      serviceAccountName: helloworld-agent-sa
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .KubeConfigSecret }}
      {{- if eq .InstallMode "Hosted" }}
      - name: managed-kubeconfig-secret
        secret:
          secretName: {{ .ExternalManagedConfigSecret }}
      {{- end }}
      containers:
      - name: helloworld-agent
        image: {{ .Image }}
        imagePullPolicy: Always
        args:
          - "/helloworld"
          - "agent"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .ClusterName }}"
          {{- if eq .InstallMode "Hosted" }}
          - "--managed-kubeconfig=/managed/config/kubeconfig"
          {{- end }}
          - "--addon-namespace={{ .AddonInstallNamespace }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
          {{- if eq .InstallMode "Hosted" }}
          - name: managed-kubeconfig-secret
            mountPath: "/managed/config"
            readOnly: true
          {{- end }}
