{{- if eq .InstallMode "Hosted" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helloworld-agent
  namespace: {{ .AddonInstallNamespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: [ "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
{{- end }}