apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-manager-controller
  labels:
    app: addon-manager-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addon-manager-controller
  template:
    metadata:
      labels:
        app: addon-manager-controller
    spec:
      serviceAccountName: addon-manager-sa
      containers:
        - name: addon-manager-controller
          image: quay.io/open-cluster-management/addon-manager:latest
          imagePullPolicy: IfNotPresent
          args:
            - "/addon-manager"
            - "manager"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true