kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:addonplacementscorecollect:agent
  namespace: {{ .ClusterName }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["addonplacementscores"]
    verbs: ["*"]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores/status" ]
    verbs: [ "update", "patch" ]

