---
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mqtt
spec:
  ports:
  - name: mosquitto
    protocol: TCP
    port: 1883
    targetPort: 1883
  selector:
    name: mosquitto
  sessionAffinity: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mosquitto
  namespace: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
          name: mosquitto
        volumeMounts:
        - name: mosquitto-persistent-storage
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mosquitto-persistent-storage
        emptyDir: {}
      - name: mosquitto-config
        configMap:
          name: mosquitto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: mqtt
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
