
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-addon-open-cluster-management-io-v1alpha1-managedclusteraddon
  failurePolicy: Fail
  name: mmanagedclusteraddon.kb.io
  rules:
  - apiGroups:
    - addon.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclusteraddons
