kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "helloworldhelm.name" . }}-agent-sa
  namespace: {{ .Values.addonInstallNamespace }}
  labels:
    app: {{ template "helloworldhelm.name" . }}
    chart: {{ template "helloworldhelm.chart" . }}
    release: {{ .Release.Name }}
