# permissions for end users to view managedclusteraddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedclusteraddon-viewer-role
rules:
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/status
  verbs:
  - get
