kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworldhosted-controller
  labels:
    app: helloworldhosted-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldhosted-controller
  template:
    metadata:
      labels:
        app: helloworldhosted-controller
    spec:
      serviceAccountName: helloworldhosted-addon-sa
      containers:
      - name: helloworldhosted-controller
        image: quay.io/open-cluster-management/addon-examples
        imagePullPolicy: IfNotPresent
        env:
          - name: EXAMPLE_IMAGE_NAME
            value: $(EXAMPLE_IMAGE_NAME)
        args:
          - "/helloworld_hosted"
          - "controller"
