apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: global
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
