apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: hello-template
  namespace: cluster1
spec:
  customizedVariables:
  - name: LOG_LEVEL
    value: "4"
