apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "addon.open-cluster-management.io"
    resources:
      - managedclusteraddons
    verbs:
      - get
      - list
      - watch
