apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: helloworldhelm
  namespace: cluster1
  annotations:
    "addon.open-cluster-management.io/values": '{"global":{"imageOverrides":{"helloWorldHelm":"quay.io/open-cluster-management/helloworld-addon:latest"}}}'
spec:
  installNamespace: open-cluster-management-agent-addon
